### ISSUE TITLE
If multiple timelines are used they create duplicated id values

### ISSUE THREAD

**Issue by ktschmincke** [Asymmetrik/sentio#49]
For example, if rt-timeline and timeline are used on the same page, they will both define elements with `plot_timeline_line_<timestamp>` ids which can potentially cause accessibility issues and will be flagged by most automated a11y checkers.

Not sure what the fix is. Maybe if we allowed for a custom id to be passed in? Or something to append to the generated id?

**Comment by reblace** [comment]
I replaced the id generation with a real uuid implementation. Should address this problem. It's out in v5.0.4
